
#cd mongodb-main
#
#echo "Load CataLogues Service Schema"
#mongo < catalogue.js &>>LOG_FILE
#StatusCheck $?
#
#echo "Load Users Service Schema"
#mongo < users.js &>>LOG_FILE
#StatusCheck $?
#

- name: Setup MongoDB Repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install Mongodb Package
  ansible.builtin.yum:
    name: mongo-org
    state: installed

- name: Update MongoDB Listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Mongodb Service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Downloading Mongod Schema
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

