

- name: Add the Application User
  ansible.builtin.user:
    name: roboshop

- name: removing old web contents
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Downloading Application Content
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Copy te extracted APP content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop